import test from 'node:test'
import assert from 'node:assert/strict'
import bcrypt from 'bcrypt'
import { JSDOM } from 'jsdom'
import { Editor } from '@tiptap/core'
import { createEditorExtensions } from '../src/admin/editorExtensions.js'

const dom = new JSDOM('<!doctype html><html><body></body></html>', { pretendToBeVisual: true })
for (const name of ['window', 'document', 'navigator', 'HTMLElement', 'Element', 'Node', 'MutationObserver', 'DOMParser', 'getComputedStyle']) {
  Object.defineProperty(globalThis, name, { value: name === 'window' ? dom.window : dom.window[name], configurable: true })
}
globalThis.requestAnimationFrame = dom.window.requestAnimationFrame.bind(dom.window)
globalThis.cancelAnimationFrame = dom.window.cancelAnimationFrame.bind(dom.window)

function withEditor(content, check) {
  const element = document.createElement('div')
  document.body.append(element)
  const editor = new Editor({ element, extensions: createEditorExtensions(), content })
  try { check(editor) } finally { editor.destroy(); element.remove() }
}

test('bcrypt 6 verifies a synthetic hash generated by bcrypt 5', async () => {
  const legacy = '$2b$04$XorfI7ejcQ.iS0ayUjwiWeMJtGFrUJ7/u9og2tvgIzuvadZpi3AEq'
  assert.equal(await bcrypt.compare('dependency-upgrade-fixture', legacy), true)
  assert.equal(await bcrypt.compare('wrong-password', legacy), false)
  const fresh = await bcrypt.hash('new-test-password', 4)
  assert.equal(await bcrypt.compare('new-test-password', fresh), true)
})

test('editor preserves existing Quill HTML formatting and images', () => {
  const html = '<h2>Cloud notes</h2><p><strong>Bold</strong> <em>Italic</em> <u>Underline</u> <s>Strike</s> <a href="https://example.com">Reference</a><img src="data:image/png;base64,aGVsbG8=" alt="Uploaded image"></p><ol><li>First</li></ol><ul><li>Bullet</li></ul><blockquote>Quote</blockquote><pre class="ql-syntax" spellcheck="false">const aws = true;\n</pre>'
  withEditor(html, editor => {
    const saved = editor.getHTML()
    for (const tag of ['h2', 'strong', 'em', 'u', 's', 'ol', 'ul', 'blockquote', 'pre']) assert.ok(saved.includes(`<${tag}>`), tag)
    assert.ok(saved.includes('https://example.com'))
    assert.ok(saved.includes('data:image/png;base64,aGVsbG8='))
    assert.ok(saved.includes('const aws = true;'))
    withEditor(saved, reopened => assert.equal(reopened.getHTML(), saved))
  })
})

test('editor supports formatting, undo, reset and HTML updates', () => {
  withEditor('<p>Cloud</p>', editor => {
    editor.commands.selectAll()
    editor.commands.toggleBold()
    assert.match(editor.getHTML(), /<strong>Cloud<\/strong>/)
    editor.commands.undo()
    assert.equal(editor.getHTML(), '<p>Cloud</p>')
    editor.commands.setContent('<h3>Another post</h3>', { emitUpdate: false })
    assert.equal(editor.getText().trim(), 'Another post')
    assert.equal(editor.view.dom.querySelector('h3')?.textContent, 'Another post')
    editor.commands.clearContent()
    assert.equal(editor.isEmpty, true)
  })
})

test('editor drops scripts, event handlers and unsafe URL schemes', () => {
  withEditor('<p>Hello<script>alert(1)</script><a href="javascript:alert(1)">link</a><img src="javascript:alert(1)"><img src="https://example.com/image.png" onerror="alert(1)"><img src="data:image/svg+xml;base64,PHN2Zz4="></p>', editor => {
    const html = editor.getHTML()
    assert.doesNotMatch(html, /<script|onerror|javascript:|data:image\/svg/i)
    assert.ok(html.includes('https://example.com/image.png'))
  })
})

